### ISSUE TITLE
Retina File Handling?

### ISSUE THREAD

**Issue by brianfeister** [times/cardkit-v2#18]
@chrishutchinson, thank you so much for this!  My company will need to generate templated assets and this is exactly what we needed! :+1: 

I understand that this is a complex issue and have a good idea of what all it entails, but I was curious if you had given any thought to handling images when the originating device is a retina display.  Perhaps, the library could depend on Modernizr (optionally) and output images scaled according to the user's originating device.  Granted, the bridge from Retina => Standard resolution is always going to throw people off. Right now, when I create an image on a Retina device and save it, opening it later in Photoshop produces a 1/2 sized image.  I'm only speaking from the perspective of user's who don't understand the moving parts under the hood.  For me, I plan to integrate in such a way that the images will be streamed via base64 data blob upload to my backend.  It would be great to have the library configurable to send the x2 (retina) resolution image to my backend, where I can then create two assets by scaling down, rather than stretching the image and scaling the smaller one up.

Does that make sense?  Have you given any thought to it?  I might be able to lend a hand if we can agree on a good approach and exactly how the feature might work. Cheers!

**Comment by chrishutchinson** [comment]
Hey,

Yeah this is a good point - I've got this issue logged (#8) in order to export retina images where possible. There's currently an issue I've got to resolve with canvas elements on retina devices that should hopefully allow us to export 2x images, which will be a big bonus!

In the meantime, are you going to stream direct from CardKit to your back end system? If so, you could double the width and height of your CardKit SVG element, and scale it down on your server-side, allowing you to produce retina graphics. This would also work if you are saving the images from CardKit and uploading to your backend.

Let me know if that makes sense, and I'll try and prioritise resolving issue #8, as it's something I need to sort for one of my uses for CardKit!

**Comment by chrishutchinson** [comment]
Hi,

See my comment on #7 - I think this is not an issue, I have added the ability to export in 2x resolution, which should resolve that issue for all.

Let me know if I still haven't quite addressed this for you!

**Comment by brianfeister** [comment]
Sorry for the delayed response @chrishutchinson, but yes, your comment from #7 works for me. Thanks!
